/*
  DATA.JS — Banco de contenidos de la app
  =========================================
  Para AÑADIR UN BLOQUE NUEVO: copia un bloque entero (desde { hasta }),
  pégalo antes del cierre "];" y cambia title, titleEN y las 20 frases.

  Para AÑADIR FRASES a un bloque existente: añade una línea más dentro
  de "pairs" con el formato ["Frase en español.","Sentence in English."]
  (no olvides la coma al final de la línea anterior).

  Después de editar este archivo:
   1. Sube de nuevo los archivos a tu hosting (ver README.md).
   2. Sube en 1 el número de CACHE_VERSION en service-worker.js.
   Así los usuarios verán el aviso de "nueva versión disponible".
*/
const DATA = [
{"title":"Herramientas y equipos de montaje","titleEN":"Assembly Tools and Equipment","pairs":[
["Necesito una llave dinamométrica de 10 milímetros.","I need a 10-millimeter torque wrench."],
["Esta remachadora neumática no funciona correctamente.","This pneumatic rivet gun isn't working properly."],
["¿Dónde están los calibres de espesor?","Where are the thickness gauges?"],
["Hay que calibrar el torquímetro antes del turno.","The torque wrench must be calibrated before the shift."],
["El taladro de precisión está fuera de servicio.","The precision drill is out of service."],
["Guarda las herramientas en su sitio al terminar.","Put the tools back in place when you're done."],
["¿Puedes prestarme un destornillador de estrella?","Can you lend me a Phillips screwdriver?"],
["La caja de herramientas debe revisarse cada mañana.","The toolbox must be checked every morning."],
["Este par de apriete no es el correcto.","This torque value is not correct."],
["Necesitamos más brocas para el aluminio.","We need more drill bits for the aluminum."],
["La herramienta está desgastada y hay que sustituirla.","The tool is worn and needs to be replaced."],
["Registra el número de serie de la herramienta.","Record the tool's serial number."],
["Este equipo requiere mantenimiento preventivo mensual.","This equipment requires monthly preventive maintenance."],
["¿Has verificado la presión del compresor?","Have you checked the compressor's pressure?"],
["El puesto de trabajo debe estar limpio y ordenado.","The workstation must be clean and tidy."],
["Usa siempre la herramienta adecuada para cada tarea.","Always use the right tool for each task."],
["Esta llave no encaja en el tornillo.","This wrench doesn't fit the bolt."],
["El taller cuenta con herramientas certificadas por el fabricante.","The workshop has manufacturer-certified tools."],
["Avísame si detectas algún fallo en el equipo.","Let me know if you find any fault with the equipment."],
["Antes de empezar, comprueba que todo esté calibrado.","Before starting, check that everything is calibrated."]
]},
{"title":"Materiales y estructuras aeronáuticas","titleEN":"Aircraft Materials and Structures","pairs":[
["El fuselaje está fabricado en aluminio de alta resistencia.","The fuselage is made of high-strength aluminum."],
["Esta pieza es de fibra de carbono.","This part is made of carbon fiber."],
["El material compuesto reduce el peso de la estructura.","The composite material reduces the structure's weight."],
["Hay que revisar si hay corrosión en el larguero.","We need to check for corrosion on the spar."],
["Esta chapa tiene un espesor de dos milímetros.","This sheet is two millimeters thick."],
["El revestimiento exterior protege contra la fatiga estructural.","The outer skin protects against structural fatigue."],
["Los remaches deben ser compatibles con el material.","The rivets must be compatible with the material."],
["Esta costilla forma parte del ala.","This rib is part of the wing."],
["El titanio se usa en zonas de alta temperatura.","Titanium is used in high-temperature areas."],
["La estructura primaria soporta las cargas principales.","The primary structure carries the main loads."],
["Hay una grieta visible en el panel.","There is a visible crack in the panel."],
["Este componente requiere tratamiento anticorrosivo.","This component requires anti-corrosion treatment."],
["El larguerillo refuerza el revestimiento del fuselaje.","The stringer reinforces the fuselage skin."],
["Verifica el número de lote del material.","Check the material's batch number."],
["Esta unión estructural debe cumplir la tolerancia especificada.","This structural joint must meet the specified tolerance."],
["El material compuesto se inspecciona con ultrasonidos.","The composite material is inspected using ultrasound."],
["La estructura secundaria no soporta cargas críticas.","The secondary structure doesn't carry critical loads."],
["Este panel de acceso permite la inspección interna.","This access panel allows internal inspection."],
["El certificado de material debe archivarse con la orden de trabajo.","The material certificate must be filed with the work order."],
["Cada lote de material lleva su propia trazabilidad.","Each material batch has its own traceability record."]
]},
{"title":"Remachado y elementos de fijación","titleEN":"Riveting and Fasteners","pairs":[
["Este remache está mal colocado.","This rivet is incorrectly placed."],
["Necesitamos remaches ciegos para esta zona.","We need blind rivets for this area."],
["El diámetro del remache no coincide con el orificio.","The rivet diameter doesn't match the hole."],
["Aplica el par de apriete indicado en el manual.","Apply the torque value specified in the manual."],
["Esta tuerca autoblocante no debe reutilizarse.","This self-locking nut must not be reused."],
["El perno tiene que estar centrado en el taladro.","The bolt must be centered in the drilled hole."],
["Usa un pasador de seguridad en esta unión.","Use a safety pin on this joint."],
["La distancia entre remaches debe respetar el plano.","The spacing between rivets must follow the blueprint."],
["Este tornillo está pasado de rosca.","This screw is cross-threaded."],
["Comprueba que la arandela esté bien asentada.","Check that the washer is properly seated."],
["El remache saliente puede causar interferencia aerodinámica.","A protruding rivet can cause aerodynamic interference."],
["Este taladro guía asegura la alineación correcta.","This pilot hole ensures correct alignment."],
["La unión atornillada necesita frenado químico.","The bolted joint needs thread-locking compound."],
["Sustituye cualquier fijación dañada antes de continuar.","Replace any damaged fastener before continuing."],
["El par de apriete se verifica con la llave dinamométrica.","The torque value is checked with the torque wrench."],
["Esta zona requiere remaches de cabeza avellanada.","This area requires countersunk rivets."],
["El proceso de remachado debe seguir la orden de trabajo.","The riveting process must follow the work order."],
["No fuerces el remache si no entra correctamente.","Don't force the rivet if it doesn't fit properly."],
["Verifica la holgura antes de cerrar la unión.","Check the clearance before closing the joint."],
["Cada fijación debe quedar registrada en el informe.","Every fastener must be recorded in the report."]
]},
{"title":"Lectura de planos e instrucciones técnicas","titleEN":"Reading Blueprints and Technical Instructions","pairs":[
["Consulta el plano antes de perforar.","Check the blueprint before drilling."],
["Esta cota indica la distancia exacta entre agujeros.","This dimension shows the exact distance between holes."],
["El plano incluye la lista de materiales.","The blueprint includes the bill of materials."],
["Sigue las instrucciones paso a paso del manual técnico.","Follow the technical manual instructions step by step."],
["Esta vista muestra la sección transversal de la pieza.","This view shows the part's cross-section."],
["El símbolo indica una soldadura en esa zona.","The symbol indicates a weld in that area."],
["Revisa la escala del plano antes de medir.","Check the blueprint's scale before measuring."],
["La orden de trabajo especifica la revisión aplicable.","The work order specifies the applicable revision."],
["Este documento está actualizado a la última versión.","This document is updated to the latest version."],
["Verifica que estás usando el plano correcto.","Make sure you're using the correct blueprint."],
["La leyenda explica los símbolos utilizados.","The legend explains the symbols used."],
["Esta nota técnica modifica el procedimiento original.","This technical note modifies the original procedure."],
["El manual indica la secuencia de montaje.","The manual indicates the assembly sequence."],
["Comprueba la referencia de la pieza en el catálogo.","Check the part reference in the catalog."],
["Esta tolerancia dimensional es crítica para el ensamblaje.","This dimensional tolerance is critical for assembly."],
["El plano muestra la posición exacta del sensor.","The blueprint shows the sensor's exact position."],
["Firma la orden de trabajo al completar la tarea.","Sign the work order upon completing the task."],
["Este boletín de servicio afecta a este modelo.","This service bulletin affects this model."],
["Consulta al ingeniero si el plano genera dudas.","Ask the engineer if the blueprint raises questions."],
["Archiva la documentación técnica según el procedimiento.","File the technical documentation according to procedure."]
]},
{"title":"Sistemas hidráulicos y neumáticos","titleEN":"Hydraulic and Pneumatic Systems","pairs":[
["Hay una fuga en la línea hidráulica.","There's a leak in the hydraulic line."],
["Comprueba la presión del sistema antes de operar.","Check the system pressure before operating."],
["Esta manguera hidráulica está desgastada.","This hydraulic hose is worn out."],
["El actuador no responde correctamente.","The actuator isn't responding properly."],
["Purga el aire del circuito hidráulico.","Bleed the air from the hydraulic circuit."],
["Este componente neumático controla el tren de aterrizaje.","This pneumatic component controls the landing gear."],
["Verifica el nivel de fluido hidráulico.","Check the hydraulic fluid level."],
["La válvula reguladora está bloqueada.","The regulating valve is stuck."],
["Este sistema opera a alta presión.","This system operates at high pressure."],
["Sustituye el filtro hidráulico según el intervalo indicado.","Replace the hydraulic filter according to the specified interval."],
["El cilindro hidráulico presenta corrosión externa.","The hydraulic cylinder shows external corrosion."],
["Comprueba las conexiones en busca de fugas.","Check the connections for leaks."],
["Este acumulador mantiene la presión constante.","This accumulator maintains constant pressure."],
["El sistema neumático alimenta los frenos.","The pneumatic system feeds the brakes."],
["Reemplaza la junta tórica dañada.","Replace the damaged O-ring."],
["La bomba hidráulica funciona con normalidad.","The hydraulic pump is functioning normally."],
["Este manómetro indica la presión del circuito.","This pressure gauge shows the circuit's pressure."],
["Realiza la prueba funcional tras la reparación.","Perform the functional test after the repair."],
["El fluido hidráulico debe cumplir la especificación indicada.","The hydraulic fluid must meet the specified requirement."],
["Documenta cualquier anomalía detectada en el sistema.","Document any anomaly detected in the system."]
]},
{"title":"Sistemas eléctricos y aviónica","titleEN":"Electrical Systems and Avionics","pairs":[
["Este cable está mal conectado.","This cable is incorrectly connected."],
["Comprueba la continuidad con el multímetro.","Check the continuity with the multimeter."],
["El conector presenta un pin doblado.","The connector has a bent pin."],
["Esta unidad de aviónica requiere calibración.","This avionics unit requires calibration."],
["Verifica el fusible antes de energizar el sistema.","Check the fuse before powering the system."],
["El mazo de cables debe estar bien sujeto.","The wiring harness must be properly secured."],
["Este sensor envía una señal errónea.","This sensor is sending a faulty signal."],
["La pantalla de la cabina no enciende.","The cockpit display isn't turning on."],
["Comprueba el aislamiento del cableado.","Check the wiring insulation."],
["Este disyuntor ha saltado repetidamente.","This circuit breaker has tripped repeatedly."],
["El sistema eléctrico funciona dentro de los parámetros.","The electrical system is operating within parameters."],
["Etiqueta cada cable según el esquema eléctrico.","Label each wire according to the wiring diagram."],
["Este componente de aviónica está certificado.","This avionics component is certified."],
["Realiza la prueba de aislamiento antes de cerrar el panel.","Perform the insulation test before closing the panel."],
["La batería debe revisarse periódicamente.","The battery must be checked periodically."],
["Este relé controla el encendido del sistema.","This relay controls the system's activation."],
["Verifica la puesta a tierra de la estructura.","Check the structure's grounding."],
["El software de aviónica necesita actualizarse.","The avionics software needs to be updated."],
["Este indicador muestra un fallo intermitente.","This indicator shows an intermittent fault."],
["Documenta cualquier cambio en el sistema eléctrico.","Document any change to the electrical system."]
]},
{"title":"Seguridad laboral y normativa (EASA/FAA)","titleEN":"Workplace Safety and Regulations (EASA/FAA)","pairs":[
["Usa siempre el equipo de protección individual.","Always wear personal protective equipment."],
["Esta tarea requiere autorización previa.","This task requires prior authorization."],
["Consulta la normativa EASA antes de proceder.","Check EASA regulations before proceeding."],
["El procedimiento debe cumplir los estándares de la FAA.","The procedure must comply with FAA standards."],
["Reporta cualquier incidente de seguridad de inmediato.","Report any safety incident immediately."],
["Este objeto extraño debe retirarse del área de trabajo.","This foreign object must be removed from the work area."],
["La zona está señalizada por riesgo eléctrico.","The area is marked due to electrical hazard."],
["Verifica que el área esté despejada antes de operar.","Make sure the area is clear before operating."],
["Este procedimiento de bloqueo evita accidentes.","This lockout procedure prevents accidents."],
["La inspección de seguridad es obligatoria antes del vuelo.","The safety inspection is mandatory before flight."],
["Este manual cumple con la normativa vigente.","This manual complies with current regulations."],
["Firma el registro de seguridad al finalizar.","Sign the safety log when finished."],
["El uso de guantes es obligatorio en esta zona.","Wearing gloves is mandatory in this area."],
["Esta directiva de aeronavegabilidad debe aplicarse.","This airworthiness directive must be applied."],
["El programa FOD evita daños por objetos extraños.","The FOD program prevents damage from foreign objects."],
["Cualquier no conformidad debe documentarse.","Any non-conformity must be documented."],
["Este equipo cumple con los requisitos de certificación.","This equipment meets certification requirements."],
["La auditoría de calidad revisará este proceso.","The quality audit will review this process."],
["Detén el trabajo si detectas un riesgo grave.","Stop work if you detect a serious hazard."],
["La formación en seguridad se renueva anualmente.","Safety training is renewed annually."]
]},
{"title":"Inspección y control de calidad","titleEN":"Inspection and Quality Control","pairs":[
["Esta pieza no ha superado la inspección.","This part has failed inspection."],
["El inspector debe validar el trabajo antes de continuar.","The inspector must validate the work before continuing."],
["Esta medida está fuera de tolerancia.","This measurement is out of tolerance."],
["Registra el resultado de la inspección visual.","Record the result of the visual inspection."],
["El componente requiere una inspección por líquidos penetrantes.","The component requires a penetrant inspection."],
["Esta no conformidad debe reportarse al departamento de calidad.","This non-conformity must be reported to the quality department."],
["Verifica la trazabilidad de la pieza sustituida.","Check the traceability of the replaced part."],
["El informe de calidad debe firmarse por el supervisor.","The quality report must be signed by the supervisor."],
["Esta muestra se enviará al laboratorio para su análisis.","This sample will be sent to the lab for analysis."],
["El control dimensional confirma que la pieza es correcta.","The dimensional check confirms the part is correct."],
["Esta discrepancia debe cerrarse antes de la entrega.","This discrepancy must be closed before delivery."],
["El sello de calidad certifica que el trabajo es conforme.","The quality stamp certifies the work is compliant."],
["Realiza una doble verificación en tareas críticas.","Perform a double check on critical tasks."],
["Este defecto es superficial y no afecta la estructura.","This defect is superficial and doesn't affect the structure."],
["La inspección final se realiza antes de la entrega del avión.","The final inspection is carried out before aircraft delivery."],
["Este certificado de conformidad acompaña a la pieza.","This certificate of conformity accompanies the part."],
["El registro de calidad debe conservarse durante años.","The quality record must be kept for years."],
["Esta pieza ha sido rechazada por el control de calidad.","This part has been rejected by quality control."],
["Verifica que la herramienta de medición esté calibrada.","Make sure the measuring tool is calibrated."],
["Cada tarea crítica requiere una firma de inspección independiente.","Every critical task requires an independent inspection signature."]
]},
{"title":"Motores y sistemas de propulsión","titleEN":"Engines and Propulsion Systems","pairs":[
["El motor presenta una vibración anormal.","The engine shows abnormal vibration."],
["Comprueba el nivel de aceite del motor.","Check the engine's oil level."],
["Esta turbina requiere una revisión programada.","This turbine requires a scheduled overhaul."],
["El álabe de la turbina está dañado.","The turbine blade is damaged."],
["Verifica la temperatura de los gases de escape.","Check the exhaust gas temperature."],
["Este cojinete presenta desgaste excesivo.","This bearing shows excessive wear."],
["El sistema de combustible necesita inspección.","The fuel system needs inspection."],
["Esta fuga de aceite proviene del sello del motor.","This oil leak comes from the engine seal."],
["El compresor del motor gira con normalidad.","The engine compressor is turning normally."],
["Este parámetro está fuera del rango operativo.","This parameter is outside the operating range."],
["La góndola del motor debe cerrarse correctamente.","The engine nacelle must be closed properly."],
["Este motor ha completado el número de ciclos permitido.","This engine has completed the allowed number of cycles."],
["Verifica el par de apriete de los pernos del motor.","Check the torque of the engine bolts."],
["La prueba de arranque se realizará mañana.","The start-up test will be carried out tomorrow."],
["Este filtro de combustible debe sustituirse.","This fuel filter must be replaced."],
["El motor auxiliar suministra energía en tierra.","The auxiliary power unit supplies power on the ground."],
["Esta hélice presenta una muesca en el borde.","This propeller shows a nick on the edge."],
["Registra las horas de funcionamiento del motor.","Record the engine's operating hours."],
["Este sistema de encendido funciona correctamente.","This ignition system is working properly."],
["La inspección boroscópica revela el estado interno del motor.","The borescope inspection reveals the engine's internal condition."]
]},
{"title":"Comunicación en equipo y documentación de trabajo","titleEN":"Team Communication and Work Documentation","pairs":[
["Informa al supervisor cuando termines la tarea.","Inform the supervisor when you finish the task."],
["Esta orden de trabajo debe cerrarse hoy.","This work order must be closed today."],
["Comunica cualquier retraso al jefe de turno.","Report any delay to the shift leader."],
["Rellena el parte de trabajo con precisión.","Fill out the work report accurately."],
["Este cambio de turno requiere un traspaso claro.","This shift change requires a clear handover."],
["Explica el problema con detalle en el informe.","Explain the problem in detail in the report."],
["Este equipo trabaja de forma coordinada con calidad.","This team works in coordination with quality."],
["Firma y fecha cada documento completado.","Sign and date every completed document."],
["Solicita apoyo si la tarea supera el plazo.","Ask for support if the task exceeds the deadline."],
["Este procedimiento debe explicarse al nuevo compañero.","This procedure must be explained to the new colleague."],
["Actualiza el estado de la tarea en el sistema.","Update the task status in the system."],
["Esta reunión diaria revisa el avance del proyecto.","This daily meeting reviews the project's progress."],
["Informa de inmediato cualquier desviación del plan.","Report any deviation from the plan immediately."],
["Este informe debe redactarse en un lenguaje claro.","This report must be written in clear language."],
["Coordina con el equipo eléctrico antes de continuar.","Coordinate with the electrical team before continuing."],
["Adjunta las fotos del defecto al informe.","Attach photos of the defect to the report."],
["Este documento se archiva en el sistema de calidad.","This document is filed in the quality system."],
["Confirma la recepción de la pieza con el almacén.","Confirm receipt of the part with the warehouse."],
["Este resumen se enviará al responsable de producción.","This summary will be sent to the production manager."],
["Mantener una buena comunicación evita errores costosos.","Maintaining good communication prevents costly errors."]
]},
{"title":"Verbos y expresiones de uso diario","titleEN":"Everyday Hangar Verbs and Expressions","pairs":[
["Dar por finalizada la tarea.","To mark the task as finished."],
["Quedar pendiente de revisión.","To remain pending review."],
["Poner en marcha el sistema.","To start up the system."],
["Dejar fuera de servicio un equipo.","To take a piece of equipment out of service."],
["Dar el visto bueno al trabajo.","To give the work the go-ahead."],
["Tomar nota de cualquier incidencia.","To make a note of any issue."],
["Llevar a cabo la inspección.","To carry out the inspection."],
["Hacer un seguimiento del problema.","To follow up on the problem."],
["Ponerse al día con el turno anterior.","To catch up with the previous shift."],
["Echar un vistazo rápido antes de firmar.","To take a quick look before signing."],
["Dejar constancia por escrito.","To put it in writing."],
["Tener en cuenta la normativa vigente.","To take current regulations into account."],
["Sacar adelante el trabajo a tiempo.","To get the work done on time."],
["Volver a comprobar antes de cerrar el panel.","To double-check before closing the panel."],
["Ceñirse al procedimiento establecido.","To stick to the established procedure."],
["Dar parte de cualquier anomalía.","To report any anomaly."],
["Contar con el material necesario.","To have the necessary material on hand."],
["Encargarse de una tarea concreta.","To be in charge of a specific task."],
["Estar al tanto de los cambios de turno.","To stay informed about shift changes."],
["Cerrar sesión en el sistema al terminar.","To log out of the system when finished."]
]},
{"title":"El C295: vocabulario específico","titleEN":"The C295: Specific Vocabulary","pairs":[
["El C295 se ensambla en la planta FAL de Sevilla-San Pablo.","The C295 is assembled at the FAL plant in Seville-San Pablo."],
["Este avión monta dos motores turbohélice Pratt & Whitney PW127G.","This aircraft is fitted with two Pratt & Whitney PW127G turboprop engines."],
["La hélice de seis palas debe revisarse tras cada vuelo.","The six-blade propeller must be inspected after every flight."],
["El tren de aterrizaje es retráctil y de tipo triciclo.","The landing gear is retractable and of tricycle type."],
["Comprueba el mecanismo de la rampa de carga trasera.","Check the rear cargo ramp mechanism."],
["La bodega de carga está presurizada.","The cargo hold is pressurized."],
["Este modelo incorpora winglets en las puntas del ala.","This model features winglets on the wingtips."],
["El C295 tiene capacidad de despegue y aterrizaje cortos.","The C295 has short take-off and landing capability."],
["Verifica el freno de hélice antes de operar en modo APU.","Check the propeller brake before operating in APU mode."],
["Este avión puede repostarse en vuelo con la sonda instalada.","This aircraft can be refueled in flight with the probe installed."],
["La aviónica Pro Line Fusion equipa la cabina de mando.","The Pro Line Fusion avionics equip the cockpit."],
["Los palets de carga se aseguran mediante rieles en el suelo de la bodega.","The cargo pallets are secured using rails on the cargo hold floor."],
["Este componente forma parte del sistema de misión FITS.","This component is part of the FITS mission system."],
["El motor debe cumplir las diez mil horas de vuelo antes de taller.","The engine must reach ten thousand flight hours before overhaul."],
["La cabina del C295 no requiere presurización adicional en vuelos bajos.","The C295 cabin doesn't require extra pressurization on low-altitude flights."],
["Comprueba la integridad del cajón central del ala antes del montaje final.","Check the integrity of the center wing box before final assembly."],
["Este avión puede operar en pistas no preparadas.","This aircraft can operate on unprepared runways."],
["La compuerta de la rampa se acciona de forma hidráulica.","The ramp door is operated hydraulically."],
["Verifica el sistema de reversa de las hélices.","Check the propeller reversal system."],
["El C295 combina transporte táctico y logístico en la misma plataforma.","The C295 combines tactical and logistics transport on the same platform."]
]}
];
